name: bus_route_finder
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.2.6
  geolocator: ^14.0.0
  http: ^0.13.5
  flutter_polyline_points: ^1.0.0    # Make sure this is here!

  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  dropdown_search: ^5.0.6
  location: ^8.0.0
  permission_handler: ^11.0.0
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bus.png
    - assets/bus1.png
    - assets/bus2.png
    - assets/bu.png
